[project]
name = "wg-config"
version = "0.1.0"
description = ""
authors = [{ name = "Nima Roomi", email = "nroomia@gmail.com" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
	"wgconfig>=1.0.0,<2.0.0",
	"rich>=13.5.3,<14.0.0",
	"typer>=0.9.0,<0.10.0",
]

[project.scripts]
wg-config = "wg_config:app"

[dependency-groups]
dev = [
	"ruff>=0.15.20,<0.16",
	"pytest>=7.4.2,<8",
	"pre-commit>=3.4.0,<4",
]

[build-system]
requires = ["uv_build>=0.11,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[tool.ruff]
select = [
	"F",   # pyflakes
	"E",   # pycodestyle errors
	"W",   # pycodestyle warnings
	"I",   # isort
	"N",   # pep8-naming
	"FBT", # flake8-boolean-trap
	"B",   # flake8-bugbear
	"A",   # flake8-builtins
	"COM", # flake8-commas
	"C4",  # flake8-comprehensions
	"DTZ", # flake8-datetimez
	"SLF", # flake8-self
	"SIM", # flake8-simplify
	"ERA", # eradicate
]
ignore = [
	"E501",   # line too long, handled by the formatter
	"COM812", # trailing comma, handled by the formatter
]
ignore-init-module-imports = true

[tool.ruff.isort]
force-single-line = true
